### ISSUE TITLE
[Bug?]: CSS Module composes generation doesn't support multi composes list

### ISSUE THREAD

**Issue by caseybaggz** [pluralsight/pando#1037]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using a single composes rule in a CSS file our generation works just fine. However, if you were to use the valid multi-composes feature:

```css
composes: pandoBtn pandoDefaultRadius;
```

the plugin will only use the last item in the list to extend vs. both. This is important because the composes spec has an undefined hierarchy with file composes and requires the use of combining composes values.

### Expected behavior 🤔

The CSS module generation should support all native CSS Module features.

### Steps to reproduce 🕹

Steps:

1. Open the sandbox
2. create 2 local styles in the buttonCSS.module.css
3. add `composes: styleOne styleTwo;` to class of choice
4. SEE GENERATED FILE ONLY EXTEND THE LAST CLASS LISTED

### Context 🔦

Headless Styles, sandbox, custom plugin

**Comment by Rykus0** [comment]
This may have been fixed by the fix for #1010.  I know Tooltip positioning composes multiple local classes, and those were updated as part of that fix, but I will confirm.

**Comment by Rykus0** [comment]
Confirmed that this has been fixed

CSS
![image](https://user-images.githubusercontent.com/1745718/214681284-e9f0a596-61a7-4975-afc9-726b7cdee3c3.png)

Composed JS object
![image](https://user-images.githubusercontent.com/1745718/214681387-70c3347c-6019-4dd2-aa6c-d543e1fd2860.png)

**Comment by caseybaggz** [comment]
@Rykus0 I rebased my branch from `main` and this still isn't working. Re-opening.

**Comment by caseybaggz** [comment]
Current branch that is not working:

```css
.filledButton {
  composes: btnBase btnDefaultRadius btnDefaultBorder;
}

.outlineButton {
  composes: btnBase btnDefaultRadius;
  background-color: transparent;
  border: 2px solid var(--ps-border-strong);
  color: var(--ps-text);
}

.textButton {
  composes: btnBase btnDefaultRadius btnDefaultBorder;
  background-color: transparent;
  color: var(--ps-action-navigation);
  text-decoration: underline;
}
```

Generated JS is creating the Objects, but only applying the last property:
```javascript
filledButton: {
    ...button.pandoBtnBorder,
  },
  outlineButton: {
    ...button.pandoBtnRadius,
    backgroundColor: 'transparent',
    border: '2px solid var(--ps-border-strong)',
    color: 'var(--ps-text)',
  },
  textButton: {
    ...button.pandoBtnBorder,
    backgroundColor: 'transparent',
    color: 'var(--ps-action-navigation)',
    textDecoration: 'underline',
    '&:hover:not(:disabled)': {
      ...extract(button.pandoBtnBorder, '&:hover:not(:disabled)'),
      backgroundColor: 'transparent',
      color: 'var(--ps-action-navigation-hover)',
      textDecoration: 'none',
    },
    '&:active:not(:disabled)': {
      ...extract(button.pandoBtnBorder, '&:active:not(:disabled)'),
      backgroundColor: 'transparent',
      color: 'var(--ps-action-navigation-visited)',
    },
  },
```

**Comment by caseybaggz** [comment]
blocks #1032

**Comment by caseybaggz** [comment]
Looks like it's potentially in the compose step loop phase. I think it's because it's specifically having to compose local classes that are composing other files which makes sense because we are deep merging, it's probably just overwriting each property in the loop because...you know...Javascript. 🙈
